### ISSUE TITLE
Kiritilgan qiymatni tekshirishda kamchilik )

### ISSUE THREAD

**Issue by udilbar** [Muhammadboburshoh/temperatura#1]
![Screenshot_10](https://user-images.githubusercontent.com/68459485/98666609-12e0da80-236f-11eb-965b-4314a59b41c3.png)
Inputga string turidagi ma'lumot kiritganimizda, natijada chiquvchi NaN ning oldini olib qo'yganimiz yaxshi )

**Comment by Muhammadboburshoh** [comment]
Rahmat to'g'irlaymiz)

**Comment by Muhammadboburshoh** [comment]
To'girlani :)
